baseURL = 'https://sitorasu.github.io'
languageCode = 'ja-jp'
hasCJKLanguage = true
title = '🌊ボトルメール'
theme = 'PaperMod'

[Params]
disableSpecial1stPost = true
author = 'U+1F198'
ShowShareButtons = true

[menu]
[[menu.main]]
identifier = 'Tags'
name = "Tags"
url = "/tags/"
weight = 10
